
export const localStorageKeys = {
  NINE_BALL_GAME_SESSION: 'NINE_BALL_GAME_SESSION',
  NINE_BALL_GHOST_LIFETIME_DATA: 'NINE_BALL_GHOST_LIFETIME_DATA'
}

export const NINE_BALL_POINT_BONUS = 1;

export const NINE_BALL_GHOST_MAX_BALL_COUNT = 9;
